version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  ### PostgreSQL ###########################################
  sonar-postgres:
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=workdock
      - POSTGRES_PASSWORD=workdock
      - GITLAB_POSTGRES_INIT=true
      - GITLAB_POSTGRES_USER=workdock
      - GITLAB_POSTGRES_PASSWORD=workdock
      - GITLAB_POSTGRES_DB=workdock_sonarqube
    networks:
      - backend

  ### SONARQUBE ################################################
  sonarqube:
    build:
      context: ./sonarqube
    hostname: "sonar.pingink.local"
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9900:9000
    depends_on:
      - postgres
    environment:
      - sonar.jdbc.username=workdock
      - sonar.jdbc.password=workdock
      - sonar.jdbc.url=jdbc:postgresql://sonar-postgres:5432/workdock_sonarqube
    networks:
      - backend
      - frontend
