version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  ### redis ################################################
  elk-redis:
    build:
      context: ./redis
    networks:
      - backend

  ### logstash ################################################
  elk-logstash:
    build:
      context: ./logstash
      args:
        - ELK_VERSION=7.5.1
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './logstash/pipeline:/usr/share/logstash/pipeline'
    environment:
      LS_JAVA_OPTS: '-Xmx1g -Xms1g'
    networks:
      - backend

  ### elasticsearch ################################################
  elk-elasticsearch:
    build:
      context: ./elasticsearch
      args:
        - ELK_VERSION=7.5.1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=workdock-cluster
      - node.name=workdock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=workdock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - backend

  ### kibana ################################################
  kibana:
    build:
      context: ./kibana
      args:
        - ELK_VERSION=7.5.1
    volumes:
      - './kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml'
    ports:
      - "5601:5601"
    networks:
      - frontend
      - backend
